[package]
name = "lightdas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
blockbuster = "1.0.1"
dotenv = "0.15.0"
futures = "0.3.30"
lazy_static = "1.4.0"
solana-client = "1.16.2"
solana-rpc-client-api = "1.16.2"
solana-sdk = "1.16.27"
solana-transaction-status = "1.16.2"
tokio = "1.36.0"
